app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey
eureka:
  client:
    healthcheck:
      enabled: true
    lease:
      duration: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 5
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 9991
service:
  event-service:
    serviceId: event-service
  zuul:
    serviceId: zuul
spring:
  application:
    name: user-service
  boot:
    admin:
      client:
        password: 123456
        url: http://localhost:8761/admin
        username: user
  datasource:
    initialization-mode: always
    password: anchal29
    url: jdbc:mysql://localhost:3306/alpha?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
