spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
        git:
          uri: https://github.com/mathuranchal73/config-server-repo
          clone-on-start: false
  profiles:
     active: native
  security:
    user:
      password: $2y$06$l7Hlob2bykTl5DhQG/ZPMeAbwY4DRZAnsyo4er1xk2E8CeHT.wJkG
     ## password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888

app:
  password: 1234